version: "3.8"

services:
  backend:
    build: ./backend
    container_name: bible-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: bible-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
